views.py
# -*- coding: utf-8 -*-

from flask import request, render_template, redirect, Blueprint, flash, url_for, make_response
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, current_user, logout_user
from datetime import datetime
from collections import namedtuple

from .constants import MONTHS
from .tools import delta_to_hms
from .models import User, Wday, Break
from . import db
from . import cache

HMS = namedtuple('HMS', ['start', 'stop', 'duration', 'done'])

common = Blueprint('common', __name__)


@common.route('/', methods=['GET'])
def main_page():
    cuser = User.check_anon(current_user)
    day = cuser.day(tuple(request.args.values())) if request.args else cuser.day()

    if day is not None:
        print(Wday().get_breaks())
        cache.set(cuser.pk, day.pk)
        break_now = Break.today(day).filter_by(actual=True).first()
        is_pause = 1 if break_now else 0
        month_start, month_stop = MONTHS[day.start.month], MONTHS[day.finish.month]
        today = HMS(day.start, day.finish, delta_to_hms(day.finish-day.start), day.done)
        breaks_sum = day.calc_breaks()
        breaks_sum = delta_to_hms(breaks_sum) if breaks_sum else ''
    else:
        is_pause, today, breaks_sum, month_start, month_stop = 0, None, '', '', ''

    return render_template('calend.html', cuser=cuser, breaks_sum=breaks_sum, is_pause=is_pause, today=today,
                           month_start=month_start, month_stop=month_stop)


@common.route('/refreshtimer', methods=['GET'])
def refresh_timer():
    if request.args.get('do') is not None:
        cuser = User.check_anon(current_user)
        day = cuser.day() if cache.get(cuser.pk) is None else Wday.by_pk(cache.get(cuser.pk))
        if day is not None:
            left = day.left()
            left['now'], left['max'] = (day.finish - datetime.now()).seconds, (day.finish - day.start).seconds
        else:
            left = dict(getHours=0, getMinutes=0, getSeconds=0, now=0, max=100)
        return left


@common.route('/refreshbreaks', methods=['GET'])
def refresh_breaks():
    if request.args.get('do') is not None:
        cuser = User.check_anon(current_user)
        day = cuser.day() if cache.get(cuser.pk) is None else Wday.by_pk(cache.get(cuser.pk))
        res = day.breaks_strings() if day is not None else ''
        return dict(breaks=res)


@common.route('/setday', methods=['GET'])
def setday():
    cuser = User.check_anon(current_user)
    day = Wday.by_user_today(cuser)
    if request.args.get("paused") is not None:
        if day is not None and day.finish > datetime.now():
            actual_break = Break.today(day).filter_by(actual=True).first()
            if actual_break:  # уже на паузе
                actual_break.close()
            else:
                db.session.add(Break(day_pk=day.pk, actual=True))
                db.session.commit()
        return dict(done='ok')
    if request.args.get("started") is not None:
        return dict(started=1) if day is not None and day.finish > datetime.now() else dict(started=0)


@common.route('/', methods=['POST'])
def set_day():
    print(request.form)
    cuser = User.check_anon(current_user)
    day = Wday.by_user_today(cuser)
    if request.form.get("begindStore") is not None:
        if cuser and day is None:
            begind = int(request.form.get("begindStore"))
            day = Wday(user_pk=cuser.pk, longitude=begind)
            day.update_session()
            day.finish = day.calc_finish()
            day.update_session()
    if request.form.get("changedStore") is not None:
        if day is not None and day.finish > datetime.now():
            day.longitude = int(request.form.get("changedStore"))
            day.update_session()
            day.finish = day.calc_finish()
            day.update_session()
    if request.form.get("finishd") is not None:
        if day is not None:
            day.finish = datetime.now()
            day.done = True
            day.update_session()
            day.longitude = day.recalc_longitude()
            day.update_session()
    if request.form.get("resetd") is not None:
        if day is not None:
            db.session.delete(day)
            db.session.commit()
    return redirect(url_for('common.main_page'))


@common.route('/profile')
@login_required
def profile_page():
    return render_template('profile.html', cuser=current_user)


auth = Blueprint('auth', __name__)


@auth.route('/login')
def login_page():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post_page():
    username = request.form.get('username')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(name=username).first()

    if not user or not check_password_hash(user.password, password):
        flash('Введён неверный пароль, либо пользователь не существует')
        return redirect(url_for('auth.login_page'))

    login_user(user, remember=remember)
    return redirect(url_for('common.main_page'))


@auth.route('/signup')
def signup_page():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post_page():
    email, name, password = request.form.get('email'), request.form.get('name'), request.form.get('password')
    user = User.query.filter_by(name=name).first()

    if user:
        flash('Пользователь уже зарегистрирован')
        return redirect(url_for('auth.signup_page'))

    db.session.add(User(email=email, password=generate_password_hash(password, method='sha256'), name=name))
    db.session.commit()

    return redirect(url_for('auth.login_page'))


@auth.route('/logout')
def logout_page():
    logout_user()
    return redirect(url_for('common.main_page'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TC | {%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Nunito">
    <link rel="stylesheet" href="/css/clock.css" />
    <script src="/js/clock.js"></script>
    <script src="/js/event-handlers.js"></script>
    <script src="/js/vanilla-calendar.js"></script>

  <style>

      .cast { background: #00D1B2; }
      body { font-family: 'Nunito';}

      div.clock-dyn {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translateX(-50%) translateY(-50%);
        color: #FFFFFF;
          font-size: 78px;
          font-weight: bold;
        letter-spacing: 12px;
      }
  </style>

</head>
<body class="cast">
<nav class="navbar navbar-light navbar-expand-md fixed-top">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            {% block navLeft %}{% endblock %}
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto text-white" href="{{ url_for('common.main_page') }}"><h2><b>TimeCounter</b></h2></a>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('common.profile_page') }}"><h4><b>Профиль</b></h4></a>
            </li>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login_page') }}"><h4><b>Авторизоваться</b></h4></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup_page') }}"><h4><b>Регистрация</b></h4></a>
            </li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout_page') }}"><h4><b>Выход</b></h4></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container-fluid mt-5 pt-5">

{% block content %} {% endblock %}



</div>
{% block scripts %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

templates/calend-fish.html
{% extends "base.html" %}

        {% block content %}

<div class="row">

    <div class="col-3">
        {% if current_user.is_authenticated %}{% block calendar %}{% endblock %}{% endif %}
    </div>
    <div class="col-5 pl-0 pr-0 ml-0 mr-0" style="border-width:30px">
        {% if current_user.is_authenticated %}{% block timer %}{% endblock %}{% endif %}
    </div>

    <div class="col-3 pl-5 pr-5">
        {% block watches %}{% endblock %}
    </div>
    <div class="col-1"></div>
</div>
<div class="row mt-5 mb-5"></div>
{% if current_user.is_authenticated %}
{% block control %}{% endblock %}

<div class="row mt-5 mb-5"></div>

<div class="row">{% block breaks %}{% endblock %}</div>

{% endif %}
{% endblock %}

templates/calend.html
{% extends "calend-fish.html" %}


{%block title%}
    Main
{%endblock%}

{% block navLeft %}
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#"><h4>Статистика <b>{{cuser.name}}</b></h4></a>
            </li>
            {% endif %}
{% endblock %}

{% block mainHello %}
    <a>Главная страница, Добро пожаловать!!!</a>
{% endblock %}


{% block calendar %}
    <div id="myCalendar" class="vanilla-calendar"></div>
    <link rel="stylesheet" href="/css/vanilla-calendar.css">

{% endblock %}

{% block timer %}
      <div id="MyClockDisplay" class="clock-dyn" onload="checkPause()"></div>
{% endblock %}

{% block watches %}
    <div class="clock">
        <div class="wrap"></div>
        <span class="hour"></span>
        <span class="minute"></span>
        <span class="second"></span>
        <span class="dot"></span>
    </div>

{% endblock %}



{% block control %}
<div class="row" id="rowRange">
    <div class="col-2 mr-0 pr-0 ml-5 pl-5"></div>
    <div class="col-7 pt-0 pb-2">
        <div class="input-group">
            <input type="range" class="custom-range" min="1" max="16" id="begind" value="8" oninput="updateRange(value);">
        </div>
    </div>
    <div class="col-2 ml-5 mr-5"></div>
</div>

<div class="row pb-3">
    <div class="col-2 mr-0 pr-0 ml-5 pl-5 text-white">
        {% if today %}<h4><b>
         {{today.start.day}} {{month_start}} | {{today.start.strftime('%H')}}:{{today.start.strftime('%M')}}:{{today.start.strftime('%S')}}
        </b></h4>{% endif %}
    </div>
            <div class="col-7">
                <div class="progress" style="height: 30px; font-size: 150%;">
                    <div id="bar" class="progress-bar progress-bar-striped bg-info progress-bar-animated" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
    <div class="col-2 ml-5 mr-5 text-white">
        {% if today %}<h4><b>
        {{today.stop.strftime('%H')}}:{{today.stop.strftime('%M')}}:{{today.stop.strftime('%S')}} | {{today.stop.day}} {{month_stop}}
        </b></h4>{% endif %}
    </div>
</div>
<div class="row" id="rowBegind" >
    <div class="col-2 mr-0 pr-0 ml-5 pl-5"></div>
    <div class="col-7 pt-0 pb-2">
        <form method="POST" action="/">
            <div class="input-group">
                <input type="number" id="begindStore" name="begindStore" min="1" max="16" value="8" style = "display: none;">
                <br><br>
                <button class="btn btn-outline-light btn-block"><b>Старт</b></button>
            </div>
        </form>
    </div>
    <div class="col-2 ml-5 mr-5"></div>
</div>
<div class="row" id="rowChanged" style = "display: none;">
    <div class="col-2 mr-0 pr-0 ml-5 pl-5"></div>
    <div class="col-7 pt-0 pb-2">
        <form method="POST" action="/">
            <div class="input-group">
                <input type="number" id="changedStore" name="changedStore" min="1" max="16" value="8" style = "display: none;">
                <br><br>
                <button class="btn btn-outline-light btn-block"><b>Изменить</b></button>
            </div>
        </form>
    </div>
    <div class="col-2 ml-5 mr-5"></div>
</div>
<div class="row" id="rowControl" >
    <div class="col-2 mr-0 pr-0 ml-5 pl-5"></div>
    <div class="col-7 pt-0 pb-2">
        <div class="row">
        <div class="col-3 pr-0 mr-0">
                <div class="input-group">
                    <button class="btn btn-outline-light btn-block" id="btnChg" value="0" onclick="clickChange()"><b>Изменить</b></button>
                </div>
        </div>
    <div class="col-3 p-0 m-0">
        <form method="POST" action="/">
            <div class="input-group">
                <button class="btn btn-info btn-block" id="finishd" name="finishd" value="{{today.done}}"><b>Завершить</b></button>
            </div>
        </form>
    </div>
    <div class="col-3 p-0 m-0">
        <div class="input-group">
            <button class="btn btn-info btn-block text-white" id="paused" name="paused" value="{{is_pause}}" onclick="clickPause(value)"></button>
        </div>
    </div>
    <div class="col-3 pl-0 ml-0">
                <form method="POST" action="/">
            <div class="input-group">
                <button class="btn btn-danger btn-block" name="resetd" value="true"><b>Сбросить</b></button>
            </div>
        </form>

    </div>
        </div>
    </div>
    <div class="col-2 ml-5 mr-5"></div>
</div>
{% endblock %}

{% block breaks %}

<div class="row"></div>

<div id="Breaks"></div>
        {% if today and today.done%}
        <br>
            Продолжительность составила: {{today.duration}}
            {% if breaks_sum %}
                <br>
                при этом, суммарно перерывов на: {{ breaks_sum }}
            {%endif%}
        {%endif%}

{% endblock %}

        {% block scripts %}

<script type="text/javascript">

clock();

let DateToShow = new Date();
{% if today %}
DateToShow.setDate({{today.start.day}});
DateToShow.setMonth({{today.start.month-1}});
DateToShow.setYear({{today.start.year}});
{% endif %}

setCalendar(DateToShow);


//window.onload = daysDone();
window.onload = hasDayStarted();
window.onload = refreshBreaks();
window.onload = setPauseLabel();

</script>
{% endblock %}

templates/login.html
{% extends "base.html" %}

        {%block title%}SignIn{%endblock%}

{% block content %}
<div class="row">
</div>
<div class="row fixed-middle">

    <div class="col-4"></div>
    <div class="col border rounded border-white  shadow p-3 mb-5 bg-white">
    <h3 class="title">Авторизация</h3>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <p>{{ messages[0] }}</p>
    {% endif %}

    {% endwith %}

        <form method="POST" action="/login">


            <div class="form-group">

                <input class="form-control form-control input-lg" type="username" name="username" placeholder="Username" autofocus="">

            </div>


            <div class="form-group">

                <input class="form-control form-control input-lg" type="password" name="password" placeholder="Пароль">

            </div>
            <div class="form-row form-check">
                <div class="col-12">
                <input type="checkbox" class="form-check-input" id="passCheck">
                <label class="form-check-label" for="passCheck">запомнить</label>
                </div>
            </div>

            <button type="submit" class="btn btn-primary btn-block">Войти</button>


        </form>
    </div>

    <div class="col-4"></div>

</div>
<div class="row h-100">
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

        {%block title%}Profile{%endblock%}

{% block content %}
<h1 class="title">
  Доброе пожаловать {{name}}!
</h1>
        <a>Можно изменить пароль, изменить почту. Отправить статистику на почту.</a>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

        {%block title%}SignUp{%endblock%}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">

        {% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}. Go to <a href="{{ url_for('auth.login_page') }}">страница авторизации</a>.
    </div>
{% endif %}
{% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}